name: docker-compose-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      libraryName: medical-pi
      targetZip: medical-pi-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v3
      
      - name: Build the stack
        run: docker-compose up --build && docker-compose down

      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/src/build/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
